version: 2

sources:
  - name: snowflake_sample
    description: Snowflake sample dataset
    database: SNOWFLAKE_SAMPLE_DATA
    schema: TPCH_SF1
    tables: 
      - name: customer
      - name: nation