name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: install and docs build
        run: |
          apt-get update && apt-get install gcc -y && apt-get install git -y && apt-get clean && pip install virtualenv
          apt-get install graphviz -y
          virtualenv venv
          . venv/bin/activate
          python -V
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install git+https://github.com/sphinx-contrib/prefecttask
          cd sp-docs/
          sphinx-build -b html . ../docs
