name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: install and docs build
        run: |
          sudo apt-get update && apt-get install gcc -yqq && apt-get install git -yqq && apt-get clean \
          && rm -rf /var/lib/apt/lists/* && pip install virtualenv
          apt-get install graphviz -y
          virtualenv venv
          . venv/bin/activate
          python -V
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install git+https://github.com/sphinx-contrib/prefecttask
          cd sp-docs/
          sphinx-build -b html . ../docs
