name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      # Standard drop-in approach that should work for most people.
      - uses: ammaraskar/sphinx-action@master
        with:
          build-command: "sphinx-build -b html . ../docs"
          docs-folder: "sp-docs/"
